SRC       += src/patch.cc src/feature.cc src/feature_selector.cc src/classifier.cc src/data_source.cc src/image_util.cc src/util.cc
SRC       += src/detector.cc

PROTO_SRC += src/patch.proto src/feature.proto src/classifier.proto

MAIN_SRC  += src/load.cc src/train.cc src/predict.cc src/detect.cc